;; testLoadSkill - Initialize Skill Environment for Unit Test
(defun testLoadSkill ()
    (printf "Loading Skill Files: \"%s/*.il\"\n" 
	    (axlGetVariable "TEST_SKILL_DIR"))
    (foreach fileName (getDirFiles (axlGetVariable "TEST_SKILL_DIR"))
	(when (equal (cadr (parseString fileName ".")) "il")
	    (load fileName))))

(testLoadSkill)
