#!/bin/csh -f

source Version

set dest = /ccs/data/skill/examples/DOC/QIR

if ( $#argv != 0 ) then
    if ("$argv[1]" == "-d") then
        alias ct echo
	alias cp echo
    else
	echo "Args are -d or nothing"
	exit 1
    endif
else
    alias ct cleartool
endif

ct co -nc $dest/CHANGE $dest/NEW

set type = CHANGE
cd $type
set dd = $dest/$type
foreach i (*)
   set doci = 0
   if (-d $i) continue

   if (!(-e $dd/$i)) then
        ct mkelem -nc $dd/$i
        set doci = 1
	echo NEW $i
   else
        diff $i $dd/$i >&/dev/null
        set doci = $status
        if ($doci == 1) then
           ct co -nc $dd/$i
	endif
   endif

   if ($doci == 1) then
	echo CHECKIN for $i
	cp $i $dd/$i 
	if ($status) then
	  echo ERROR: Copy of $i failed
	endif
	ct ci -c "$LASTVERSION to QIR update" $dd/$i
   endif
end
cd ..

set type = NEW
cd $type
set dd = $dest/$type
foreach i (*)
   set doci = 0
   if (-d $i) continue

   if (!(-e $dd/$i)) then
        ct mkelem -nc $dd/$i
        set doci = 1
	echo NEW $i
   else
        diff $i $dd/$i >&/dev/null
        set doci = $status
        if ($doci == 1) then
           ct co -nc $dd/$i
	endif
   endif

   if ($doci == 1) then
	echo CHECKIN for $i
	cp $i $dd/$i 
	if ($status) then
	  echo ERROR: Copy of $i failed
	endif
	ct ci -c "$LASTVERSION to QIR update" $dd/$i
   endif
end
cd ..

ct ci -c "$LASTVERSION to QIR update" $dest/CHANGE $dest/NEW

