#!/usr/bin/env python3
"""Render the OrCAD Capture TCL raw API index to greppable Markdown parts.

The OrCAD corpus was scanned into ``orcadcapture/.paginate/api_index_raw.json``
(5100 entries: name, signature, class, returns, file, type) but the
agent-facing Markdown index was never generated, so the runbook's lookup path
(``grep orcadcapture/api_index.part*.md``) matched nothing.

Method names repeat heavily across classes (``Next`` alone has 167 entries),
so the table carries the owning ``Class`` column; without it most rows would
be indistinguishable.  There is no line information in the raw scan - the
Source column names the file to open.

Parts are filled greedily under the same ~54K-char page budget the other
converters use (15k tokens x 4 chars x 0.9 safety).  Output is deterministic
(sorted by name, then class), so ``--check`` is a plain text comparison.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any, Dict, List, Sequence

ORCAD_ROOT = Path(__file__).resolve().parents[1] / "skill-references" / "orcadcapture"
RAW_INDEX = ORCAD_ROOT / ".paginate" / "api_index_raw.json"

# same page budget as the HTML/PDF converters: 15000 tokens * 4 chars * 0.9
PART_CHAR_BUDGET = 54_000

HEADER = """\
<!-- Generated by scripts/build_orcad_index.py; do not edit manually. -->

# OrCAD Capture TCL API Index (part {number} of {parts})

Search this file for an exact method name, disambiguate by the owning class,
then read the referenced source entry. It covers the OrCAD Capture TCL APIs
documented in capture_commands/, cis_commands/ and database_commands/.

| Name | Class | Declaration | Source |
|---|---|---|---|
"""


def _declaration(entry: Dict[str, Any]) -> str:
    signature = entry["signature"]
    returns = entry.get("returns")
    return f"{signature} => {returns}" if returns else signature


def _class(entry: Dict[str, Any]) -> str:
    return (entry.get("class") or "-").rstrip(":")


def _row(entry: Dict[str, Any]) -> str:
    return (
        f"| `{entry['name']}` | `{_class(entry)}` "
        f"| `{_declaration(entry)}` | `orcadcapture/{entry['file']}` |\n"
    )


def render(entries: Sequence[Dict[str, Any]]) -> List[str]:
    """The full part texts, in order.

    Exact duplicate rows (the scanner records the same method twice when a
    doc page repeats it) collapse to one; same-name methods on different
    classes or in different files are kept.
    """
    unique: Dict[tuple, Dict[str, Any]] = {}
    for entry in entries:
        key = (entry["name"], _class(entry), _declaration(entry), entry["file"])
        unique.setdefault(key, entry)
    ordered = sorted(
        unique.values(), key=lambda e: (e["name"].casefold(), _class(e), e["file"])
    )
    parts: List[List[str]] = [[]]
    used = len(HEADER)
    for entry in ordered:
        row = _row(entry)
        if used + len(row) > PART_CHAR_BUDGET and parts[-1]:
            parts.append([])
            used = len(HEADER)
        parts[-1].append(row)
        used += len(row)
    return [
        HEADER.format(number=index + 1, parts=len(parts)) + "".join(rows)
        for index, rows in enumerate(parts)
    ]


def part_paths(root: Path, count: int) -> List[Path]:
    return [root / f"api_index.part{index + 1:02d}.md" for index in range(count)]


def main(argv: List[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=ORCAD_ROOT)
    parser.add_argument("--check", action="store_true",
                        help="verify the on-disk parts match a fresh render")
    args = parser.parse_args(argv)
    root = args.root

    raw_path = root / ".paginate" / "api_index_raw.json"
    entries = json.loads(raw_path.read_text(encoding="utf-8"))
    parts = render(entries)
    row_count = sum(part.count("\n| `") for part in parts)

    if args.check:
        stale = []
        expected = part_paths(root, len(parts))
        for path, text in zip(expected, parts):
            if not path.is_file() or path.read_text(encoding="utf-8") != text:
                stale.append(path.name)
        extra = sorted(root.glob("api_index.part*.md"))
        if len(extra) != len(expected):
            stale.append(f"part count differs ({len(extra)} on disk vs {len(expected)})")
        if stale:
            for name in stale:
                print(f"error: stale OrCAD index: {name}; run build_orcad_index.py")
            return 1
        print(f"ok: {len(parts)} OrCAD index parts up to date ({len(entries)} scanned, {row_count} unique rows)")
        return 0

    for stale in root.glob("api_index.part*.md"):
        stale.unlink()
    for path, text in zip(part_paths(root, len(parts)), parts):
        path.write_text(text, encoding="utf-8")
    print(f"wrote {len(parts)} OrCAD index parts ({len(entries)} scanned, {row_count} unique rows) under {root}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
