#!/usr/bin/env python3
"""Convert bundled Cadence SKILL PDF references into searchable Markdown parts."""

from __future__ import annotations

import argparse
import math
import re
import shutil
import subprocess
from pathlib import Path
from typing import Dict, List, NamedTuple, Optional, Sequence, Tuple

TOKEN_LIMIT = 15_000
SAFETY_RATIO = 0.9
CHARS_PER_TOKEN = 4.0
# Reserve space for the generated title, page headings, and normalized declarations.
PART_CHAR_LIMIT = math.floor(TOKEN_LIMIT * SAFETY_RATIO * CHARS_PER_TOKEN) - 2_000
DOCUMENT_TITLES = {
    "skipcref": "Cadence Interprocess Communication SKILL Reference",
    "skdevref": "Cadence SKILL Development Reference",
    "skoopref": "Cadence SKILL++ Object System Reference",
}
EXPECTED_PHYSICAL_PAGES = {"skipcref": 56, "skdevref": 162, "skoopref": 72}
EXPECTED_API_ENTRIES = {"skipcref": 22, "skdevref": 90, "skoopref": 42}
API_NAME = re.compile(
    r"[A-Za-z][A-Za-z0-9_+*?<>:-]*(?:,\s*[A-Za-z][A-Za-z0-9_+*?<>:-]*)*"
)
GENERATED_HEADER = "<!-- Generated by scripts/convert_pdf_references.py; do not edit manually. -->"


class ApiDeclaration(NamedTuple):
    names: Tuple[str, ...]
    signature: str


def _extract_pdf_text(path: Path) -> str:
    executable = shutil.which("pdftotext")
    if executable is None:
        raise RuntimeError("pdftotext is required to convert bundled PDF references")
    result = subprocess.run(
        [executable, "-layout", str(path), "-"],
        check=False,
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        detail = result.stderr.strip() or f"exit status {result.returncode}"
        raise RuntimeError(f"pdftotext failed for {path}: {detail}")
    return result.stdout


def _pdf_pages(text: str) -> List[str]:
    pages = text.replace("\r\n", "\n").replace("\r", "\n").split("\f")
    while pages and not pages[-1].strip():
        pages.pop()
    return [page.rstrip() for page in pages]


def extract_api_declarations(page: str) -> List[ApiDeclaration]:
    """Extract formal declarations, excluding examples that merely call an API."""
    lines = [line.strip() for line in page.splitlines()]
    declarations: List[ApiDeclaration] = []
    for index, value in enumerate(lines):
        if API_NAME.fullmatch(value) is None:
            continue
        names = tuple(name.strip() for name in value.split(","))
        cursor = index + 1
        while cursor < len(lines) and not lines[cursor]:
            cursor += 1
        if cursor >= len(lines) or not lines[cursor].startswith(f"{names[0]}("):
            continue
        signature_lines: List[str] = []
        for candidate in lines[cursor : cursor + 30]:
            if candidate:
                signature_lines.append(candidate)
            if "=>" in candidate:
                break
        if not signature_lines or "=>" not in signature_lines[-1]:
            continue
        declaration = ApiDeclaration(names, " ".join(signature_lines))
        if declaration not in declarations:
            declarations.append(declaration)
    return declarations


def _render_page(page: str, physical_page: int) -> str:
    lines = [f"## PDF page {physical_page}", ""]
    declarations = extract_api_declarations(page)
    for declaration in declarations:
        escaped_signature = declaration.signature.replace("`", "\\`")
        lines.extend(
            [
                f"### {', '.join(declaration.names)}",
                "",
                f"`{escaped_signature}`",
                "",
            ]
        )
    lines.extend(["```text", page, "```", ""])
    return "\n".join(lines)


def render_document(stem: str, pages: Sequence[str]) -> List[str]:
    if stem not in DOCUMENT_TITLES:
        raise ValueError(f"unsupported PDF reference: {stem}")
    atomic_chunks: List[str] = []
    current_api: List[str] = []
    seen_api = False
    for index, page in enumerate(pages, start=1):
        page_chunk = _render_page(page, index)
        if extract_api_declarations(page):
            if current_api:
                atomic_chunks.append("".join(current_api))
            current_api = [page_chunk]
            seen_api = True
        elif seen_api:
            current_api.append(page_chunk)
        else:
            atomic_chunks.append(page_chunk)
    if current_api:
        atomic_chunks.append("".join(current_api))

    parts: List[str] = []
    current: List[str] = []
    current_chars = 0
    for chunk in atomic_chunks:
        if current and current_chars + len(chunk) > PART_CHAR_LIMIT:
            parts.append("".join(current))
            current = []
            current_chars = 0
        current.append(chunk)
        current_chars += len(chunk)
    if current:
        parts.append("".join(current))

    rendered: List[str] = []
    for part_number, body in enumerate(parts, start=1):
        rendered.append(
            f"{GENERATED_HEADER}\n\n"
            f"# {DOCUMENT_TITLES[stem]} - Part {part_number:02d}\n\n"
            f"Source: `docs/{stem}.pdf`. Physical PDF page numbers are preserved below.\n\n"
            f"{body}"
        )
    return rendered


def expected_outputs(root: Path, stems: Sequence[str]) -> Dict[Path, str]:
    outputs: Dict[Path, str] = {}
    for stem in stems:
        source = root / "docs" / f"{stem}.pdf"
        if not source.is_file():
            raise FileNotFoundError(source)
        pages = _pdf_pages(_extract_pdf_text(source))
        if len(pages) != EXPECTED_PHYSICAL_PAGES[stem]:
            raise RuntimeError(
                f"{source.name} has {len(pages)} pages; expected "
                f"{EXPECTED_PHYSICAL_PAGES[stem]}"
            )
        api_count = sum(
            len(declaration.names)
            for page in pages
            for declaration in extract_api_declarations(page)
        )
        if api_count != EXPECTED_API_ENTRIES[stem]:
            raise RuntimeError(
                f"{source.name} yielded {api_count} API entries; expected "
                f"{EXPECTED_API_ENTRIES[stem]}"
            )
        for index, content in enumerate(render_document(stem, pages), start=1):
            outputs[root / stem / f"{stem}.part{index:02d}.md"] = content
    return outputs


def build(root: Path, stems: Sequence[str]) -> None:
    outputs = expected_outputs(root, stems)
    for stem in stems:
        destination = root / stem
        destination.mkdir(exist_ok=True)
        expected_paths = {path for path in outputs if path.parent == destination}
        for old_path in destination.glob(f"{stem}.part*.md"):
            if old_path not in expected_paths:
                old_path.unlink()
    for path, content in outputs.items():
        path.write_text(content, encoding="utf-8")


def check(root: Path, stems: Sequence[str]) -> List[str]:
    outputs = expected_outputs(root, stems)
    errors: List[str] = []
    for path, expected in outputs.items():
        if not path.is_file() or path.read_text(encoding="utf-8") != expected:
            errors.append(f"stale converted reference: {path.relative_to(root)}")
    for stem in stems:
        destination = root / stem
        expected_paths = {path for path in outputs if path.parent == destination}
        for path in destination.glob(f"{stem}.part*.md") if destination.is_dir() else ():
            if path not in expected_paths:
                errors.append(f"unexpected converted reference part: {path.relative_to(root)}")
    return errors


def _default_root() -> Path:
    return Path(__file__).resolve().parents[1] / "skill-references"


def main(argv: Optional[Sequence[str]] = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=_default_root())
    parser.add_argument("--check", action="store_true")
    parser.add_argument("documents", nargs="*", choices=sorted(DOCUMENT_TITLES))
    arguments = parser.parse_args(argv)
    root = arguments.root.resolve()
    stems = tuple(arguments.documents or sorted(DOCUMENT_TITLES))
    if arguments.check:
        errors = check(root, stems)
        for error in errors:
            print(f"error: {error}")
        return 1 if errors else 0
    build(root, stems)
    print(f"converted {', '.join(stems)} under {root}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
