import importlib.util
import json
import sys
import tempfile
import unittest
from pathlib import Path

SCRIPTS_DIR = Path(__file__).parents[1] / "scripts"


def load_module(filename, module_name):
    if str(SCRIPTS_DIR) not in sys.path:
        sys.path.insert(0, str(SCRIPTS_DIR))
    spec = importlib.util.spec_from_file_location(module_name, SCRIPTS_DIR / filename)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"cannot load {filename}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


INDEX = """\
<!-- Generated by scripts/build_reference_indexes.py; do not edit manually. -->

# axl* API Index (part 1 of 1)

| Symbol | Documented declaration | Source | Line |
|---|---|---|---:|
| `axlDbidName` | `axlDbidName( o_dbid ) => t_name/nil` | `algroskill/dbidname.md` | 17 |
| `axlRenameNet` | `axlRenameNet( t_old_name t_new_name ) => t/nil` | `algroskill/renamenet.md` | 3 |
"""


def evidence(**overrides):
    entry = {
        "api": "axlDbidName",
        "source": "algroskill/dbidname.md",
        "line": 17,
        "signature": "axlDbidName( o_dbid ) => t_name/nil",
        "returns": "t_name/nil",
        "constraints": "",
        "platform": "",
    }
    entry.update(overrides)
    return entry


class VerifyAssessmentTestBase(unittest.TestCase):
    def setUp(self):
        self.verify_assessment = load_module("verify_assessment.py", "verify_assessment")
        self.temp_dir = tempfile.TemporaryDirectory()
        self.root = Path(self.temp_dir.name) / "skill-references"
        self.root.mkdir(parents=True)
        (self.root / "api_index.part01.md").write_text(INDEX, encoding="utf-8")
        sys.path.insert(0, str(SCRIPTS_DIR))
        import validate_skill_api

        self.specs = validate_skill_api.load_corpus(self.root)

    def tearDown(self):
        self.temp_dir.cleanup()

    def check(self, entries):
        return self.verify_assessment.verify_evidence(entries, self.specs)

    def codes(self, entries):
        return [(f.level, f.check) for f in self.check(entries)]


class EvidenceVerificationTests(VerifyAssessmentTestBase):
    def test_fully_correct_evidence_has_no_findings(self):
        self.assertEqual(self.check([evidence()]), [])

    def test_unknown_api_is_an_error_with_suggestions(self):
        findings = self.check([evidence(api="axlNetNameGet")])
        self.assertEqual([(f.level, f.check) for f in findings], [("error", "api-unknown")])
        self.assertIn("did you mean", findings[0].detail)

    def test_unknown_api_error_names_real_candidates(self):
        # the suggestion must be a symbol that actually exists in the corpus
        findings = self.check([evidence(api="axlRenameNetX")])
        self.assertIn("axlRenameNet", findings[0].detail)

    def test_invented_api_without_candidates_still_errors(self):
        findings = self.check([evidence(api="axlZzzQqq")])
        self.assertEqual(findings[0].check, "api-unknown")

    def test_wrong_source_is_an_error(self):
        findings = self.check([evidence(source="algroskill/other.md")])
        self.assertEqual([(f.level, f.check) for f in findings], [("error", "source-mismatch")])
        self.assertIn("algroskill/dbidname.md", findings[0].detail)

    def test_wrong_line_is_only_a_warning(self):
        self.assertEqual(self.codes([evidence(line=999)]), [("warning", "line-mismatch")])

    def test_wrong_signature_is_an_error(self):
        findings = self.check([evidence(signature="axlDbidName( o_dbid t_extra ) => t_name/nil")])
        self.assertEqual([(f.level, f.check) for f in findings], [("error", "signature-mismatch")])

    def test_signature_whitespace_is_normalized(self):
        self.assertEqual(
            self.check([evidence(signature="axlDbidName(o_dbid)   =>   t_name/nil")]), []
        )

    def test_signature_may_omit_the_return_part(self):
        self.assertEqual(self.check([evidence(signature="axlDbidName( o_dbid )")]), [])

    def test_empty_api_name_is_an_error(self):
        self.assertEqual(self.codes([evidence(api="")]), [("error", "api-empty")])

    def test_omitted_optional_fields_are_not_findings(self):
        entry = {"api": "axlDbidName"}
        findings = self.check([entry])
        self.assertEqual(findings, [])

    def test_multiple_entries_report_independently(self):
        findings = self.check(
            [evidence(), evidence(api="axlBogus"), evidence(api="axlRenameNet", source="algroskill/renamenet.md", line=3, signature="axlRenameNet( t_old_name t_new_name ) => t/nil")]
        )
        self.assertEqual([(f.level, f.check) for f in findings], [("error", "api-unknown")])


class SignatureMatchingTests(VerifyAssessmentTestBase):
    def test_exact_match(self):
        self.assertTrue(
            self.verify_assessment._signature_matches(
                "axlDbidName( o_dbid ) => t_name/nil", "axlDbidName( o_dbid ) => t_name/nil"
            )
        )

    def test_extra_whitespace_collapses(self):
        self.assertTrue(
            self.verify_assessment._signature_matches(
                "axlDbidName(  o_dbid )\n=> t_name/nil", "axlDbidName( o_dbid ) => t_name/nil"
            )
        )

    def test_different_arguments_do_not_match(self):
        self.assertFalse(
            self.verify_assessment._signature_matches(
                "axlDbidName( o_dbid o_other )", "axlDbidName( o_dbid ) => t_name/nil"
            )
        )


class MainTests(VerifyAssessmentTestBase):
    def write_assessment(self, payload_entries):
        path = Path(self.temp_dir.name) / "assessment.json"
        path.write_text(
            json.dumps(
                {
                    "agent": "cadence-skill-agent",
                    "phase": "assessment",
                    "payload": {"api_evidence": payload_entries},
                }
            ),
            encoding="utf-8",
        )
        return str(path)

    def run_main(self, path):
        return self.verify_assessment.main([path, "--root", str(self.root)])

    def test_valid_assessment_exits_zero(self):
        self.assertEqual(self.run_main(self.write_assessment([evidence()])), 0)

    def test_unknown_api_exits_one(self):
        self.assertEqual(self.run_main(self.write_assessment([evidence(api="axlBogus")])), 1)

    def test_warning_only_assessment_exits_zero(self):
        self.assertEqual(self.run_main(self.write_assessment([evidence(line=999)])), 0)

    def test_empty_evidence_exits_zero_with_warning(self):
        self.assertEqual(self.run_main(self.write_assessment([])), 0)

    def test_assessment_embedded_in_prose_is_parsed(self):
        path = Path(self.temp_dir.name) / "assessment.json"
        path.write_text(
            "Here is my assessment:\n```json\n"
            + json.dumps({"payload": {"api_evidence": [evidence(api="axlBogus")]}})
            + "\n```\n",
            encoding="utf-8",
        )
        self.assertEqual(self.run_main(str(path)), 1)


if __name__ == "__main__":
    unittest.main()
