import importlib.util
import sys
import tempfile
import unittest
from pathlib import Path

SCRIPTS_DIR = Path(__file__).parents[1] / "scripts"


def load_module(filename, module_name):
    if str(SCRIPTS_DIR) not in sys.path:
        sys.path.insert(0, str(SCRIPTS_DIR))
    spec = importlib.util.spec_from_file_location(module_name, SCRIPTS_DIR / filename)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"cannot load {filename}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


AXL_INDEX = """\
<!-- Generated by scripts/build_reference_indexes.py; do not edit manually. -->

# axl* API Index (part 1 of 1)

| Symbol | Documented declaration | Source | Line |
|---|---|---|---:|
| `axlDbidName` | `axlDbidName( o_dbid ) => t_name/nil` | `algroskill/dbidname.md` | 1 |
| `axlRenameNet` | `axlRenameNet( t_old_name t_new_name ) => t/nil` | `algroskill/renamenet.md` | 1 |
| `axlVersion` | `axlVersion( s_option ) => g_value/nil` | `algroskill/version.md` | 1 |
"""

SKLANG_INDEX = """\
<!-- Generated by scripts/build_reference_indexes.py; do not edit manually. -->

# SKILL API Index (part 1 of 1)

| Symbol | Documented declaration | Source | Line |
|---|---|---|---:|
| `listp` | `listp( g_value ) => t / nil` | `sklangref/listp.md` | 1 |
| `sort` | `sort( l_list g_compareFn ) => l_result` | `sklangref/sort.md` | 1 |
"""

# The description that makes the canonical retrieval failure resolvable: the
# symbol name contains no "net", only the prose does.  Each body file holds one
# entry whose heading sits on line 1, matching the index line numbers above.
BODIES = {
    "algroskill/dbidname.md": """\
### axlDbidName

`axlDbidName( o_dbid ) => t_name/nil`

#### Description

Provides the standard Allegro PCB Editor name of a database object. Many of the
named Allegro PCB Editor objects (for example, nets) have names defined in the
name attribute.

#### Arguments

| Name | Description |
|---|---|
| `o_dbid` | Any named database object. |
""",
    "algroskill/renamenet.md": """\
### axlRenameNet

`axlRenameNet( t_old_name t_new_name ) => t/nil`

#### Description

Renames a net in the design.
""",
    "algroskill/version.md": """\
### axlVersion

`axlVersion( s_option ) => g_value/nil`

#### Description

Returns Allegro PCB Editor or OS dependent data.
""",
    "sklangref/listp.md": """\
### listp

`listp( g_value ) => t / nil`

#### Description

Checks if an object is a list.
""",
    "sklangref/sort.md": """\
### sort

`sort( l_list g_compareFn ) => l_result`

#### Description

Sorts a list using the supplied comparison function.
""",
}


class SearchTestBase(unittest.TestCase):
    def setUp(self):
        self.search_api = load_module("search_api.py", "search_api")
        self.temp_dir = tempfile.TemporaryDirectory()
        self.root = Path(self.temp_dir.name) / "skill-references"
        (self.root / "algroskill").mkdir(parents=True)
        (self.root / "sklangref").mkdir(parents=True)
        (self.root / "api_index.part01.md").write_text(AXL_INDEX, encoding="utf-8")
        (self.root / "sklang_api_index.part01.md").write_text(
            SKLANG_INDEX, encoding="utf-8"
        )
        for relative, body in BODIES.items():
            (self.root / relative).write_text(body, encoding="utf-8")

    def tearDown(self):
        self.temp_dir.cleanup()

    def index(self, domains=None):
        return self.search_api.build_index(self.root, domains)

    def names(self, query, limit=5, domains=None):
        return [m.entry.name for m in self.index(domains).search(query, limit=limit)]


class StemmingTests(SearchTestBase):
    def test_plural_is_folded_to_singular(self):
        self.assertEqual(self.search_api._stem("nets"), "net")
        self.assertEqual(self.search_api._stem("names"), "name")
        self.assertEqual(self.search_api._stem("pins"), "pin")

    def test_properties_stems_to_property(self):
        self.assertEqual(self.search_api._stem("properties"), "property")

    def test_exceptions_are_left_alone(self):
        for word in ("class", "bus", "alias", "status", "bias"):
            self.assertEqual(self.search_api._stem(word), word)

    def test_short_tokens_are_not_stemmed(self):
        self.assertEqual(self.search_api._stem("is"), "is")
        self.assertEqual(self.search_api._stem("as"), "as")

    def test_double_s_is_not_stemmed(self):
        self.assertEqual(self.search_api._stem("process"), "process")


class PredicateFormTests(SearchTestBase):
    def test_trailing_p_predicate_is_split(self):
        self.assertIn("list", self.search_api._predicate_forms("listp"))
        self.assertIn("type", self.search_api._predicate_forms("typep"))
        self.assertIn("string", self.search_api._predicate_forms("stringp"))

    def test_short_names_are_left_alone(self):
        self.assertEqual(self.search_api._predicate_forms("map"), [])
        self.assertEqual(self.search_api._predicate_forms("pp"), [])

    def test_non_predicate_ending_is_not_split(self):
        self.assertEqual(self.search_api._predicate_forms("help"), ["hel"])

    def test_predicate_name_matches_its_concept_query(self):
        # the regression this convention exists for: "list" must find listp
        self.assertEqual(self.names("is it a list")[0], "listp")


class TokenTests(SearchTestBase):
    def test_camel_case_is_split(self):
        tokens = self.search_api._tokens("axlDbidName")
        for expected in ("axldbidname", "axl", "dbid", "name"):
            self.assertIn(expected, tokens)

    def test_underscore_type_prefix_is_split(self):
        tokens = self.search_api._tokens("t_formatString")
        self.assertIn("format", tokens)
        self.assertIn("string", tokens)

    def test_intent_verbs_fold_onto_a_shared_concept(self):
        self.assertIn("GET", self.search_api._tokens("provides the name"))
        self.assertIn("GET", self.search_api._tokens("get the name"))
        self.assertIn("GET", self.search_api._tokens("returns the name"))

    def test_create_and_delete_concepts_are_distinct(self):
        self.assertIn("CREATE", self.search_api._tokens("create a net"))
        self.assertIn("DELETE", self.search_api._tokens("remove a net"))
        self.assertNotIn("CREATE", self.search_api._tokens("remove a net"))

    def test_stopwords_are_dropped(self):
        tokens = self.search_api._tokens("the quick brown fox and whether it runs")
        self.assertNotIn("the", tokens)
        self.assertNotIn("and", tokens)
        self.assertNotIn("whether", tokens)
        self.assertIn("quick", tokens)

    def test_domain_terms_are_kept(self):
        # "allegro" distinguishes an axl API from a general SKILL builtin
        self.assertIn("allegro", self.search_api._tokens("Returns Allegro data"))


class ConceptTokenTests(SearchTestBase):
    def test_intent_verb_emits_only_its_concept(self):
        # a document using the query's exact verb must not double-score against
        # a paraphrase: "gets" and "provides" index identically
        self.assertEqual(
            self.search_api._tokens("gets"), self.search_api._tokens("provides")
        )
        tokens = self.search_api._tokens("returns the name")
        self.assertIn("GET", tokens)
        self.assertNotIn("returns", tokens)
        self.assertNotIn("return", tokens)

    def test_rip_up_folds_to_delete_and_up_is_a_stopword(self):
        tokens = self.search_api._tokens("rip up the etch")
        self.assertIn("DELETE", tokens)
        self.assertNotIn("up", tokens)

    def test_concept_in_a_name_scores_at_flat_weight(self):
        # "get" in a getter's name is real signal, but not name-field signal:
        # one occurrence in the name counts the same as one in prose, or every
        # getter-named API outranks the entry matching the query's noun.
        # (the signature omits the function's own name so the name field is the
        # only source of the concept token)
        entry = self.search_api.Entry(
            name="axlGetThing",
            signature="( g_value ) => t",
            source="algroskill/getthing.md",
            line=1,
            description="",
            domain="algroskill",
        )
        index = self.search_api.SearchIndex([entry])
        self.assertEqual(
            index._frequency(0, "GET"), self.search_api.SearchIndex.CONCEPT_WEIGHT
        )

    def test_concept_frequency_still_counts_repetition(self):
        entry = self.search_api.Entry(
            name="foo",
            signature="foo( ) => t",
            source="sklangref/foo.md",
            line=1,
            description="gets and returns and fetches",
            domain="sklangref",
        )
        index = self.search_api.SearchIndex([entry])
        self.assertEqual(
            index._frequency(0, "GET"), 3 * self.search_api.SearchIndex.CONCEPT_WEIGHT
        )

    def test_return_type_is_indexed(self):
        # "string" appears only after the => : without a returns field the
        # one signal that answers "format ... as a string" would be lost
        entry = self.search_api.Entry(
            name="foo",
            signature="foo( g_value ) => t_string",
            source="sklangref/foo.md",
            line=1,
            description="",
            domain="sklangref",
        )
        index = self.search_api.SearchIndex([entry])
        self.assertEqual(
            index._frequency(0, "string"),
            self.search_api.SearchIndex.FIELD_WEIGHTS["returns"],
        )


class EmbeddedVerbTests(SearchTestBase):
    def test_lineread_splits_into_line_and_get(self):
        tokens = self.search_api._tokens("lineread")
        self.assertIn("line", tokens)
        self.assertIn("GET", tokens)

    def test_putprop_splits_and_aliased_to_property(self):
        tokens = self.search_api._tokens("putprop")
        self.assertIn("SET", tokens)
        self.assertIn("prop", tokens)
        self.assertIn("property", tokens)

    def test_remainder_too_short_is_not_split(self):
        self.assertEqual(self.search_api._embedded_verb_forms("thread"), [])
        self.assertEqual(self.search_api._embedded_verb_forms("getd"), [])

    def test_axl_names_are_not_split(self):
        # axl* names are camelCase; the lowercase path must not touch them
        self.assertEqual(self.search_api._embedded_verb_forms("axldbcreateline"), [])

    def test_prop_alias_expands_to_property(self):
        self.assertIn("property", self.search_api._tokens("props"))


class ProximityTests(SearchTestBase):
    def test_terms_meeting_in_prose_earn_a_proximity_bonus(self):
        # axlRenameNet carries "name" only in its t_old_name/t_new_name
        # arguments; axlDbidName's prose discusses nets and names together
        index = self.index()
        dbid = next(
            i for i, entry in enumerate(index.entries) if entry.name == "axlDbidName"
        )
        rename = next(
            i for i, entry in enumerate(index.entries) if entry.name == "axlRenameNet"
        )
        self.assertGreater(index._proximity_bonus(dbid, {"name", "net"}), 0.0)
        self.assertEqual(index._proximity_bonus(rename, {"name", "net"}), 0.0)

    def test_concept_tokens_do_not_participate_in_proximity(self):
        entry = self.search_api.Entry(
            name="foo",
            signature="foo( ) => t",
            source="sklangref/foo.md",
            line=1,
            description="returns the wibble",
            domain="sklangref",
        )
        index = self.search_api.SearchIndex([entry])
        # GET sits right next to "wibble" in the prose but must not count
        self.assertEqual(index._proximity_bonus(0, {"GET", "wibble"}), 0.0)

    def test_adjacent_terms_score_more_than_distant_terms(self):
        near = self.search_api.Entry(
            name="near", signature="near( ) => t", source="sklangref/a.md",
            line=1, description="wibble wobble", domain="sklangref",
        )
        far = self.search_api.Entry(
            name="far", signature="far( ) => t", source="sklangref/b.md",
            line=1,
            description="wibble " + "padding " * 20 + "wobble",
            domain="sklangref",
        )
        index = self.search_api.SearchIndex([near, far])
        self.assertGreater(
            index._proximity_bonus(0, {"wibble", "wobble"}),
            index._proximity_bonus(1, {"wibble", "wobble"}),
        )


class DescriptionAttachmentTests(SearchTestBase):
    def test_markdown_descriptions_are_attached(self):
        entries = self.search_api._load_index(self.root)
        self.search_api.attach_descriptions(self.root, entries)
        description = entries["axldbidname"].description
        self.assertIn("name of a database object", description)
        self.assertIn("nets", description)

    def test_missing_body_file_leaves_description_empty(self):
        entries = self.search_api._load_index(self.root)
        entries["axldbidname"] = entries["axldbidname"]._replace(
            source="algroskill/absent.md"
        )
        self.search_api.attach_descriptions(self.root, entries)
        self.assertEqual(entries["axldbidname"].description, "")

    def test_description_section_stops_at_next_heading(self):
        entries = self.search_api._load_index(self.root)
        self.search_api.attach_descriptions(self.root, entries)
        self.assertNotIn("o_dbid", entries["axldbidname"].description)


class RankingTests(SearchTestBase):
    def test_exact_name_match_ranks_first(self):
        self.assertEqual(self.names("axlRenameNet")[0], "axlRenameNet")

    def test_description_only_match_is_found(self):
        # the canonical failure: no "net" in the symbol name, only in the prose
        results = self.names("get the name of a net")
        self.assertIn("axlDbidName", results)

    def test_intent_query_beats_literal_wording(self):
        # documentation says "Provides", the agent asks "get"
        self.assertEqual(self.names("get the name of a net")[0], "axlDbidName")

    def test_domain_term_selects_the_allegro_api(self):
        self.assertEqual(self.names("get the Allegro version")[0], "axlVersion")

    def test_empty_query_returns_nothing(self):
        self.assertEqual(self.names("the and of"), [])

    def test_unmatched_query_returns_nothing(self):
        self.assertEqual(self.names("zzzqqq xyzzy"), [])

    def test_domain_filter_restricts_results(self):
        names = self.names("sort a list", domains=["sklangref"])
        self.assertTrue(names)
        self.assertIn("sort", names)
        for name in names:
            self.assertNotIn("axl", name.casefold())

    def test_limit_is_respected(self):
        self.assertLessEqual(len(self.names("name", limit=2)), 2)

    def test_matched_terms_are_reported(self):
        matches = self.index().search("rename a net", limit=1)
        self.assertTrue(matches)
        self.assertIn("net", matches[0].matched_terms)

    def test_term_in_several_fields_posts_the_document_once(self):
        # regression: a term occurring in both the signature and the prose was
        # posted twice, so BM25 scored that document twice and outranked entries
        # with a genuinely stronger (name-field) match
        index = self.index()
        sort_index = next(
            i for i, entry in enumerate(index.entries) if entry.name == "sort"
        )
        self.assertEqual(index.postings["list"].count(sort_index), 1)

    def test_name_field_match_outranks_prose_only_match(self):
        # listp carries "list" in its name; sort only in signature/prose
        index = self.index()
        listp_index = next(
            i for i, entry in enumerate(index.entries) if entry.name == "listp"
        )
        self.assertGreater(
            index._frequency(listp_index, "list"),
            index._frequency(
                next(
                    i for i, entry in enumerate(index.entries) if entry.name == "sort"
                ),
                "list",
            ),
        )
        self.assertEqual(self.names("is it a list")[0], "listp")


class SnippetTests(SearchTestBase):
    def test_snippet_centres_on_the_matched_term(self):
        description = "alpha " * 40 + "TARGET " + "omega " * 40
        snippet = self.search_api._snippet(description, ["target"], width=60)
        self.assertIn("TARGET", snippet)
        self.assertTrue(snippet.startswith("..."))
        self.assertTrue(snippet.endswith("..."))

    def test_snippet_of_empty_description_is_empty(self):
        self.assertEqual(self.search_api._snippet("", ["x"]), "")

    def test_snippet_without_a_match_starts_at_the_front(self):
        snippet = self.search_api._snippet("some words here", ["absent"], width=100)
        self.assertEqual(snippet, "some words here")


if __name__ == "__main__":
    unittest.main()
