import importlib.util
import io
import json
import sys
import tempfile
import unittest
from pathlib import Path

SCRIPTS_DIR = Path(__file__).parents[1] / "scripts"


def load_module(filename, module_name):
    if str(SCRIPTS_DIR) not in sys.path:
        sys.path.insert(0, str(SCRIPTS_DIR))
    spec = importlib.util.spec_from_file_location(module_name, SCRIPTS_DIR / filename)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"cannot load {filename}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


INDEX = """\
<!-- Generated by scripts/build_reference_indexes.py; do not edit manually. -->

# axl* API Index (part 1 of 1)

| Symbol | Documented declaration | Source | Line |
|---|---|---|---:|
| `axlDbidName` | `axlDbidName( o_dbid ) => t_name/nil` | `algroskill/dbidname.md` | 1 |
| `axlRenameNet` | `axlRenameNet( t_old_name t_new_name ) => t/nil` | `algroskill/renamenet.md` | 1 |
"""

BODY = """\
### axlDbidName

`axlDbidName( o_dbid ) => t_name/nil`

#### Description

Provides the standard Allegro PCB Editor name of a database object.
"""

URI = "file:///tmp/test.il"


class LspTestBase(unittest.TestCase):
    def setUp(self):
        self.skill_lsp = load_module("skill_lsp.py", "skill_lsp")
        self.temp_dir = tempfile.TemporaryDirectory()
        self.root = Path(self.temp_dir.name) / "skill-references"
        (self.root / "algroskill").mkdir(parents=True)
        (self.root / "api_index.part01.md").write_text(INDEX, encoding="utf-8")
        (self.root / "algroskill" / "dbidname.md").write_text(BODY, encoding="utf-8")
        (self.root / "algroskill" / "renamenet.md").write_text(BODY, encoding="utf-8")
        self.server = self.skill_lsp.SkillLanguageServer(self.root)

    def tearDown(self):
        self.temp_dir.cleanup()

    def open_document(self, text):
        return self.server.handle({
            "jsonrpc": "2.0",
            "method": "textDocument/didOpen",
            "params": {"textDocument": {"uri": URI, "text": text}},
        })

    def diagnostics_for(self, text):
        outgoing = self.open_document(text)
        self.assertEqual(outgoing[0]["method"], "textDocument/publishDiagnostics")
        return outgoing[0]["params"]["diagnostics"]


class ProtocolTests(LspTestBase):
    def test_initialize_advertises_capabilities(self):
        outgoing = self.server.handle(
            {"jsonrpc": "2.0", "id": 1, "method": "initialize", "params": {}}
        )
        result = outgoing[0]["result"]
        self.assertTrue(result["capabilities"]["hoverProvider"])
        self.assertTrue(result["capabilities"]["completionProvider"])
        self.assertEqual(result["capabilities"]["textDocumentSync"]["change"], 1)
        self.assertEqual(outgoing[0]["id"], 1)

    def test_unknown_request_gets_method_not_found(self):
        outgoing = self.server.handle(
            {"jsonrpc": "2.0", "id": 9, "method": "workspace/symbol", "params": {}}
        )
        self.assertEqual(outgoing[0]["error"]["code"], -32601)

    def test_unknown_notification_is_dropped(self):
        outgoing = self.server.handle({"jsonrpc": "2.0", "method": "$/cancelRequest"})
        self.assertEqual(outgoing, [])

    def test_shutdown_then_exit_status(self):
        self.server.handle({"jsonrpc": "2.0", "id": 2, "method": "shutdown"})
        self.assertTrue(self.server.shutdown_requested)


class DiagnosticsTests(LspTestBase):
    def test_clean_code_publishes_no_diagnostics(self):
        self.assertEqual(self.diagnostics_for("axlRenameNet(\"a\" \"b\")\n"), [])

    def test_unknown_axl_api_is_an_error_diagnostic(self):
        diagnostics = self.diagnostics_for("axlBogusApi(x)\n")
        self.assertEqual(len(diagnostics), 1)
        diagnostic = diagnostics[0]
        self.assertEqual(diagnostic["severity"], 1)
        self.assertEqual(diagnostic["code"], "unknown-api")
        self.assertIn("isCallable", diagnostic["message"])

    def test_diagnostic_range_covers_the_symbol(self):
        diagnostics = self.diagnostics_for("  axlBogusApi(x)\n")
        self.assertEqual(
            diagnostics[0]["range"],
            {
                "start": {"line": 0, "character": 2},
                "end": {"line": 0, "character": 2 + len("axlBogusApi")},
            },
        )

    def test_arity_mismatch_is_a_warning(self):
        diagnostics = self.diagnostics_for("axlDbidName(x y)\n")
        self.assertEqual(len(diagnostics), 1)
        self.assertEqual(diagnostics[0]["severity"], 2)
        self.assertEqual(diagnostics[0]["code"], "arity")

    def test_did_change_recomputes_diagnostics(self):
        self.open_document("axlBogusApi(x)\n")
        outgoing = self.server.handle({
            "jsonrpc": "2.0",
            "method": "textDocument/didChange",
            "params": {
                "textDocument": {"uri": URI},
                "contentChanges": [{"text": "axlRenameNet(\"a\" \"b\")\n"}],
            },
        })
        self.assertEqual(outgoing[0]["params"]["diagnostics"], [])

    def test_did_close_clears_diagnostics(self):
        self.open_document("axlBogusApi(x)\n")
        outgoing = self.server.handle({
            "jsonrpc": "2.0",
            "method": "textDocument/didClose",
            "params": {"textDocument": {"uri": URI}},
        })
        self.assertEqual(outgoing[0]["params"]["diagnostics"], [])
        self.assertNotIn(URI, self.server.documents)


class HoverTests(LspTestBase):
    def hover_at(self, text, line, character):
        self.open_document(text)
        outgoing = self.server.handle({
            "jsonrpc": "2.0", "id": 3,
            "method": "textDocument/hover",
            "params": {"textDocument": {"uri": URI},
                       "position": {"line": line, "character": character}},
        })
        return outgoing[0]["result"]

    def test_hover_on_known_symbol_returns_signature_and_source(self):
        result = self.hover_at("axlDbidName(dbid)\n", 0, 5)
        value = result["contents"]["value"]
        self.assertIn("axlDbidName( o_dbid ) => t_name/nil", value)
        self.assertIn("algroskill/dbidname.md:1", value)
        self.assertIn("name of a database object", value)

    def test_hover_on_unknown_symbol_returns_none(self):
        self.assertIsNone(self.hover_at("axlBogusApi(dbid)\n", 0, 5))

    def test_hover_off_token_returns_none(self):
        self.assertIsNone(self.hover_at("axlDbidName(dbid)\n", 0, 14))

    def test_hover_on_unopened_document_returns_none(self):
        outgoing = self.server.handle({
            "jsonrpc": "2.0", "id": 3,
            "method": "textDocument/hover",
            "params": {"textDocument": {"uri": "file:///nowhere.il"},
                       "position": {"line": 0, "character": 0}},
        })
        self.assertIsNone(outgoing[0]["result"])


class CompletionTests(LspTestBase):
    def complete_at(self, text, line, character):
        self.open_document(text)
        outgoing = self.server.handle({
            "jsonrpc": "2.0", "id": 4,
            "method": "textDocument/completion",
            "params": {"textDocument": {"uri": URI},
                       "position": {"line": line, "character": character}},
        })
        return outgoing[0]["result"]

    def test_prefix_completion_offers_matching_symbols(self):
        items = self.complete_at("axlD\n", 0, 4)
        labels = [item["label"] for item in items]
        self.assertEqual(labels, ["axlDbidName"])

    def test_completion_carries_signature_and_source(self):
        items = self.complete_at("axlRe\n", 0, 5)
        self.assertEqual(items[0]["label"], "axlRenameNet")
        self.assertEqual(items[0]["detail"], "axlRenameNet( t_old_name t_new_name ) => t/nil")
        self.assertIn("renamenet.md", items[0]["documentation"])

    def test_empty_prefix_offers_nothing(self):
        self.assertEqual(self.complete_at("  \n", 0, 2), [])


class IdentifierTests(LspTestBase):
    def test_identifier_at_cursor_positions(self):
        at = self.skill_lsp._identifier_at
        self.assertEqual(at("axlDbidName(x)", 0)[0], "axlDbidName")
        self.assertEqual(at("axlDbidName(x)", 5)[0], "axlDbidName")
        # one past the last character still counts (cursor at end of word)
        self.assertEqual(at("axlDbidName (x)", 11)[0], "axlDbidName")
        self.assertIsNone(at("axlDbidName (x)", 12))  # on the space

    def test_identifier_with_skill_sigils(self):
        at = self.skill_lsp._identifier_at
        self.assertEqual(at("  odd?(x)", 4)[0], "odd?")

    def test_word_prefix(self):
        prefix = self.skill_lsp._word_prefix
        self.assertEqual(prefix("axlD", 4), "axlD")
        self.assertEqual(prefix("foo(axlRe", 9), "axlRe")
        self.assertEqual(prefix("foo(", 4), "")


class TransportTests(LspTestBase):
    def test_message_roundtrip_through_framing(self):
        buffer = io.BytesIO()
        payload = {"jsonrpc": "2.0", "id": 1, "method": "initialize"}
        self.skill_lsp.write_message(buffer, payload)
        buffer.seek(0)
        self.assertEqual(self.skill_lsp.read_message(buffer), payload)

    def test_read_message_returns_none_on_eof(self):
        self.assertIsNone(self.skill_lsp.read_message(io.BytesIO(b"")))

    def test_serve_handles_initialize_open_exit(self):
        requests = io.BytesIO()
        for message in (
            {"jsonrpc": "2.0", "id": 1, "method": "initialize", "params": {}},
            {"jsonrpc": "2.0", "method": "textDocument/didOpen",
             "params": {"textDocument": {"uri": URI, "text": "axlBogus(x)\n"}}},
            {"jsonrpc": "2.0", "id": 2, "method": "shutdown"},
            {"jsonrpc": "2.0", "method": "exit"},
        ):
            self.skill_lsp.write_message(requests, message)
        requests.seek(0)
        responses = io.BytesIO()
        status = self.skill_lsp.serve(requests, responses, self.root)
        self.assertEqual(status, 0)
        responses.seek(0)
        messages = []
        while True:
            message = self.skill_lsp.read_message(responses)
            if message is None:
                break
            messages.append(message)
        self.assertEqual(messages[0]["id"], 1)
        self.assertEqual(messages[1]["method"], "textDocument/publishDiagnostics")
        self.assertEqual(messages[1]["params"]["diagnostics"][0]["code"], "unknown-api")
        self.assertEqual(messages[2]["id"], 2)


if __name__ == "__main__":
    unittest.main()
