import importlib.util
import sys
import tempfile
import unittest
from pathlib import Path

SCRIPTS_DIR = Path(__file__).parents[1] / "scripts"
SCRIPT_PATH = SCRIPTS_DIR / "validate_skill_api.py"


def load_validator():
    if str(SCRIPTS_DIR) not in sys.path:
        sys.path.insert(0, str(SCRIPTS_DIR))
    spec = importlib.util.spec_from_file_location("validate_skill_api", SCRIPT_PATH)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"cannot load {SCRIPT_PATH}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


AXL_INDEX = """\
<!-- Generated by scripts/build_reference_indexes.py; do not edit manually. -->

# axl* API Index (part 1 of 1)

| Symbol | Documented declaration | Source | Line |
|---|---|---|---:|
| `axlDbidName` | `axlDbidName( o_dbid ) => t_name/nil` | `algroskill/25dbmisc.md` | 10 |
| `axlDBGetDesign` | `axlDBGetDesign() => o_design/nil` | `algroskill/14dsnctl.md` | 15 |
| `axlDBCreateNet` | `axlDBCreateNet( t_netName ) => o_dbid/nil` | `algroskill/03dbcre8.md` | 20 |
| `axlSelectByName` | `axlSelectByName ( t_objectType t_name/lt_name [g_wildcard] ) => lo_dbid/nil` | `algroskill/05selfnd.md` | 30 |
| `axlDBCreateLine` | `axlDBCreateLine( l_points [f_width] [t_layer] [t_netname] [rd_parent] [s_font] ) => l_result/nil` | `algroskill/03dbcre8.md` | 40 |
| `axlCmdRegister` | `axlCmdRegister( t_allegroCmd ts_callback ?cmdType s_type ?doneCmd ts_done ) => t/nil` | `algroskill/19cmdctl.md` | 50 |
| `axlShell` | `axlShell( S_command... ) => t/nil` | `algroskill/09cmdshl.md` | 60 |
| `axlRenameNet` | `axlRenameNet( t_old_name t_new_name ) => t/nil` | `algroskill/26logacc.md` | 70 |
| `axlSetAlias` | `axlSetAlias( t_name t_alias ) => t/nil` | `algroskill/10usrint.md` | 80 |
"""

SKLANG_INDEX = """\
<!-- Generated by scripts/build_reference_indexes.py; do not edit manually. -->

# SKILL API Index (part 1 of 1)

| Symbol | Documented declaration | Source | Line |
|---|---|---|---:|
| `println` | `println( g_args... ) => g_result` | `sklangref/inputoutput.part01.md` | 5 |
| `makeTable` | `makeTable( S_name [ g_default_value ] ) => o_table` | `sklangref/datastruct.md` | 337 |
"""


class ValidatorTestBase(unittest.TestCase):
    def setUp(self):
        self.temp_dir = tempfile.TemporaryDirectory()
        self.root = Path(self.temp_dir.name) / "skill-references"
        self.root.mkdir()
        (self.root / "api_index.part01.md").write_text(AXL_INDEX, encoding="utf-8")
        (self.root / "sklang_api_index.part01.md").write_text(
            SKLANG_INDEX, encoding="utf-8"
        )
        self.validator = load_validator()
        self.specs = self.validator.load_corpus(self.root)

    def tearDown(self):
        self.temp_dir.cleanup()

    def findings(self, source, name="demo.il"):
        path = Path(self.temp_dir.name) / name
        path.write_text(source, encoding="utf-8")
        return self.validator.validate_file(path, self.root, self.specs, name)

    def checks(self, source, name="demo.il"):
        return [f.check for f in self.findings(source, name)]


class CorpusLoadingTests(ValidatorTestBase):
    def test_loads_both_indexes(self):
        self.assertIn("axldbidname", self.specs)
        self.assertIn("println", self.specs)

    def test_parses_required_and_optional_arity(self):
        spec = self.specs["axlselectbyname"]
        self.assertEqual(spec.arities[0].required, 2)
        self.assertEqual(spec.arities[0].optional, 1)
        self.assertTrue(spec.accepts(2))
        self.assertTrue(spec.accepts(3))
        self.assertFalse(spec.accepts(1))

    def test_bracketed_keyword_group_counts_as_one_optional(self):
        arity = self.validator._parse_arity(
            "loadPort( p_port [?langMode g_langMode] [?password g_password] ) => t",
        )
        self.assertEqual(arity.required, 1)
        self.assertEqual(arity.optional, 2)
        self.assertEqual(arity.keywords, ("langMode", "password"))
        # keyword args make positional counting ambiguous
        self.assertFalse(arity.countable)

    def test_variadic_signature_is_not_countable(self):
        spec = self.specs["axlshell"]
        self.assertFalse(spec.countable)
        self.assertTrue(spec.arities[0].variadic)

    def test_keyword_signature_collects_keyword_names(self):
        spec = self.specs["axlcmdregister"]
        self.assertEqual(spec.keywords, ("cmdType", "doneCmd"))
        self.assertFalse(spec.countable)

    def test_choice_group_counts_as_one_positional_slot(self):
        # t_name/lt_name is one parameter accepting either form
        self.assertEqual(self.specs["axlselectbyname"].arities[0].required, 2)

    def test_arity_summary_reads_well(self):
        self.assertEqual(self.specs["axlselectbyname"].arity_summary(), "2-3")
        self.assertEqual(self.specs["axldbidname"].arity_summary(), "1")


class UnknownApiTests(ValidatorTestBase):
    def test_invented_axl_name_is_an_error(self):
        findings = self.findings("axlGetNetByName( 'net )\n")
        self.assertEqual([f.check for f in findings], ["unknown-api"])
        self.assertEqual(findings[0].severity, "error")

    def test_error_message_suggests_real_candidates(self):
        findings = self.findings("axlRenameNetTo( o_net \"new\" )\n")
        self.assertTrue(findings)
        self.assertIn("did you mean", findings[0].message)
        self.assertIn("axlRenameNet", findings[0].message)

    def test_known_axl_name_passes(self):
        self.assertEqual(self.findings("axlDbidName( o_net )\n"), [])

    def test_verified_platform_callable_without_corpus_signature_passes(self):
        findings = self.validator.validate_text(
            "axlXSectionAssign( first second )\n",
            self.specs,
            "demo.il",
            {"axlxsectionassign"},
        )
        self.assertEqual(findings, [])

    def test_unverified_platform_callable_is_still_an_error(self):
        findings = self.validator.validate_text(
            "axlXSectionAssign( first second )\n",
            self.specs,
            "demo.il",
            set(),
        )
        self.assertEqual([finding.check for finding in findings], ["unknown-api"])

    def test_non_axl_unknown_prefix_is_out_of_scope(self):
        # dbc*/tsel*/ash* namespaces are not covered by this corpus
        self.assertEqual(self.findings("dbcFooBar( 1 2 )\ntselInit( )\n"), [])

    def test_general_skill_builtin_not_flagged_as_unknown(self):
        # the language reference does not index every SKILL builtin
        self.assertEqual(self.findings("sortcar( l_list 'alpha )\n"), [])

    def test_name_inside_comment_is_not_a_call_site(self):
        self.assertEqual(self.findings("; axlGetNetByName( x )\nprintln( 1 )\n"), [])

    def test_name_inside_string_is_not_a_call_site(self):
        self.assertEqual(self.findings('println( "axlGetNetByName( x )" )\n'), [])


class ScopeAnalysisTests(ValidatorTestBase):
    def test_locally_defined_procedure_is_not_flagged(self):
        source = (
            "procedure( axlMyHelper( x )\n"
            "  x + 1\n"
            ")\n"
            "axlMyHelper( 2 )\n"
        )
        self.assertEqual(self.findings(source), [])

    def test_let_bound_variable_is_not_flagged(self):
        source = "let( ( axlTempVar )\n  axlTempVar( 1 )\n)\n"
        self.assertEqual(self.findings(source), [])

    def test_lambda_parameter_is_not_flagged(self):
        source = "mapcar( lambda( ( axlItem ) axlItem( ) ) l_list )\n"
        self.assertEqual(self.findings(source), [])

    def test_assignment_target_is_not_flagged(self):
        source = "axlMyGlobal = 5\naxlMyGlobal( 1 )\n"
        self.assertEqual(self.findings(source), [])

    def test_foreach_variable_is_not_flagged(self):
        source = "foreach( axlEachItem l_list\n  axlEachItem( )\n)\n"
        self.assertEqual(self.findings(source), [])

    def test_defun_like_form_binds_a_name(self):
        # `define` takes the bound name as its first argument
        source = "define( axlMyFn lambda( ( x ) x ) )\naxlMyFn( 1 )\n"
        self.assertEqual(self.findings(source), [])

    def test_registering_form_does_not_bind_the_name(self):
        # defUserInitProc registers an already-existing procedure; it does not
        # define axlInitFn, so calling an undeclared one is still flagged
        source = 'defUserInitProc( "ctx" axlInitFn )\naxlInitFn( )\n'
        findings = self.findings(source)
        self.assertEqual([f.check for f in findings], ["unknown-api"])
        self.assertEqual(findings[0].line, 2)

    def test_leading_string_does_not_block_head_detection(self):
        # the bound name is still found when a literal precedes it
        source = 'defclass( "card" axlCardClass )\naxlCardClass( )\n'
        self.assertEqual(self.findings(source), [])

    def test_lisp_prefix_defun_binds_the_name(self):
        # official examples use ``(defun axlfoo_t0 () ...)`` for test helpers
        source = "(defun axlenter_t0 ()\n  (axlDbidName x)\n)\n(axlenter_t0)\n"
        self.assertEqual(self.findings(source), [])

    def test_lisp_prefix_let_binds_variables(self):
        source = "(let ( axlTempA axlTempB )\n  axlTempA = 1\n  axlTempB( 2 )\n)\n"
        self.assertEqual(self.findings(source), [])


class PrefixCallSyntaxTests(ValidatorTestBase):
    def test_prefix_call_does_not_leak_inner_arguments(self):
        # ``(null (car x))`` must count one argument for null, not two
        lexed = self.validator.strip_comments_and_strings(
            "((null (axlDbidName orderedList))\n"
        )
        sites = {s.name: s.arguments for s in self.validator.find_call_sites(lexed)}
        self.assertEqual(sites["null"], ["(axlDbidName orderedList)"])
        self.assertEqual(sites["axlDbidName"], ["orderedList"])

    def test_prefix_call_is_detected(self):
        findings = self.findings("(axlGetNetByName x)\n")
        self.assertEqual([f.check for f in findings], ["unknown-api"])

    def test_prefix_call_arity_is_checked(self):
        findings = self.findings('(axlRenameNet "old")\n')
        self.assertEqual([f.check for f in findings], ["arity"])

    def test_quoted_list_is_not_a_call_site(self):
        # '( axlFoo bar ) is data, not a call
        self.assertEqual(self.findings("l = '( axlInventedOne 1 2 )\n"), [])


class ArityTests(ValidatorTestBase):
    def test_too_few_arguments_is_an_error(self):
        findings = self.findings("axlRenameNet( \"old\" )\n")
        self.assertEqual([f.check for f in findings], ["arity"])
        self.assertIn("called with 1 argument", findings[0].message)

    def test_too_many_arguments_is_an_error(self):
        findings = self.findings('axlDbidName( o_net "extra" )\n')
        self.assertEqual([f.check for f in findings], ["arity"])

    def test_optional_argument_within_range_passes(self):
        self.assertEqual(self.findings('axlSelectByName( "net" "N1" t )\n'), [])

    def test_required_only_passes_when_optional_omitted(self):
        self.assertEqual(self.findings('axlSelectByName( "net" "N1" )\n'), [])

    def test_variadic_signature_skips_arity_check(self):
        self.assertEqual(
            self.findings('axlShell( "cmd" 1 2 3 4 5 )\n'), []
        )

    def test_keyword_signature_skips_positional_arity_check(self):
        self.assertEqual(
            self.findings("axlCmdRegister( \"cmd\" 'cb ?cmdType 'general )\n"), []
        )

    def test_arity_message_cites_signature_and_source(self):
        findings = self.findings("axlDBCreateNet( )\n")
        self.assertEqual(len(findings), 1)
        self.assertIn("axlDBCreateNet( t_netName )", findings[0].message)
        self.assertIn("algroskill/03dbcre8.md:20", findings[0].message)


class KeywordTests(ValidatorTestBase):
    def test_unknown_keyword_is_a_warning(self):
        findings = self.findings(
            "axlCmdRegister( \"cmd\" 'cb ?bogus 1 )\n"
        )
        self.assertEqual([f.check for f in findings], ["unknown-keyword"])
        self.assertEqual(findings[0].severity, "warning")

    def test_documented_keyword_passes(self):
        self.assertEqual(
            self.findings("axlCmdRegister( \"cmd\" 'cb ?cmdType 'general )\n"), []
        )


class LexingTests(ValidatorTestBase):
    def test_strip_preserves_line_numbers(self):
        lexed = self.validator.strip_comments_and_strings(
            "a\n; comment\nb\n\"str\ng\"\nc\n"
        )
        # the newline inside the unterminated string is preserved too, so the
        # author's line numbering survives lexing
        self.assertEqual(lexed.count("\n"), 6)

    def test_escaped_quote_does_not_end_string(self):
        lexed = self.validator.strip_comments_and_strings(r'"a\"b( c" ; x')
        self.assertNotIn("(", lexed.split(";")[0])

    def test_semicolon_inside_string_is_not_a_comment(self):
        # string contents are blanked, but the literal must not swallow the
        # rest of the line the way a real comment would
        lexed = self.validator.strip_comments_and_strings('println( "a;b" )')
        self.assertTrue(lexed.rstrip().endswith(")"))

    def test_string_literal_stays_one_argument_token(self):
        # a space-filled literal would be re-split into several tokens and
        # corrupt the arity count
        lexed = self.validator.strip_comments_and_strings('f( "a b c" )')
        self.assertEqual(self.validator._split_arguments(lexed[2:-2]), ['"\x00\x00\x00\x00\x00"'])

    def test_call_site_column_is_one_based(self):
        findings = self.findings("  axlGetNetByName( x )\n")
        self.assertEqual(findings[0].column, 3)

    def test_column_is_correct_after_a_preceding_string(self):
        # offset-preserving blanking keeps the reported column the author's
        findings = self.findings('println( "0123456789" ) axlGetNetByName( x )\n')
        self.assertEqual(findings[0].column, 25)

    def test_nested_calls_are_both_found(self):
        checks = self.checks("axlDbidName( axlInventedOne( x ) )\n")
        self.assertIn("unknown-api", checks)


class SuggestionTests(ValidatorTestBase):
    def test_token_overlap_ranks_related_names_first(self):
        suggestions = self.validator.suggest_candidates("axlRenameNetTo", self.specs)
        self.assertTrue(suggestions)
        self.assertEqual(suggestions[0].name, "axlRenameNet")

    def test_suggestions_are_limited(self):
        suggestions = self.validator.suggest_candidates("axlSetThing", self.specs, limit=2)
        self.assertLessEqual(len(suggestions), 2)

    def test_no_suggestions_for_unrelated_name(self):
        suggestions = self.validator.suggest_candidates("axlZzz", self.specs)
        self.assertLessEqual(len(suggestions), 3)


class OverloadTests(ValidatorTestBase):
    def test_overloaded_symbol_accepts_any_documented_form(self):
        index = AXL_INDEX + (
            "| `axlDbidName` | `axlDbidName( o_dbid t_fmt ) => t_name/nil` "
            "| `algroskill/25dbmisc.md` | 11 |\n"
        )
        (self.root / "api_index.part01.md").write_text(index, encoding="utf-8")
        specs = self.validator.load_corpus(self.root)
        self.assertEqual(len(specs["axldbidname"].arities), 2)
        self.assertEqual(specs["axldbidname"].arity_summary(), "1 or 2")

        path = Path(self.temp_dir.name) / "demo.il"
        for source in ("axlDbidName( o_net )\n", 'axlDbidName( o_net "fmt" )\n'):
            path.write_text(source, encoding="utf-8")
            self.assertEqual(
                self.validator.validate_file(path, self.root, specs, "demo.il"),
                [],
                source,
            )

        # three arguments matches neither overload
        path.write_text('axlDbidName( o_net "fmt" "extra" )\n', encoding="utf-8")
        findings = self.validator.validate_file(path, self.root, specs, "demo.il")
        self.assertEqual([f.check for f in findings], ["arity"])

    def test_variadic_overload_disables_arity_checking(self):
        index = AXL_INDEX + (
            "| `axlDbidName` | `axlDbidName( o_dbid g_args... ) => t_name/nil` "
            "| `algroskill/25dbmisc.md` | 12 |\n"
        )
        (self.root / "api_index.part01.md").write_text(index, encoding="utf-8")
        specs = self.validator.load_corpus(self.root)
        self.assertFalse(specs["axldbidname"].countable)

        path = Path(self.temp_dir.name) / "demo.il"
        path.write_text("axlDbidName( o_net 1 2 3 4 )\n", encoding="utf-8")
        self.assertEqual(
            self.validator.validate_file(path, self.root, specs, "demo.il"), []
        )


class HallucinationScenarioTests(ValidatorTestBase):
    """End-to-end: the bug class this validator exists to catch.

    ``skill_lint.py`` is purely lexical and passes all of this with exit 0, so
    these are the findings that previously reached a Windows Allegro session
    before anyone noticed the APIs did not exist.
    """

    SAMPLE = """\
procedure( myDemoScript( t_netName )
  let( ( o_net l_shapes )
    o_net = axlGetNetByName( t_netName )
    l_shapes = axlDBGetDesign()->shapes
    axlSelectByName( "NET" t_netName "ETCH" )
    axlNetRenameTo( o_net "newname" )
    t
  )
)
"""

    def test_every_invented_api_is_reported(self):
        findings = self.findings(self.SAMPLE)
        unknown = sorted(
            f.message.split("'")[1] for f in findings if f.check == "unknown-api"
        )
        self.assertEqual(unknown, ["axlGetNetByName", "axlNetRenameTo"])

    def test_real_apis_in_the_same_file_are_not_reported(self):
        findings = self.findings(self.SAMPLE)
        reported = {f.message.split("'")[1] for f in findings if f.check == "unknown-api"}
        self.assertNotIn("axlDBGetDesign", reported)
        self.assertNotIn("axlSelectByName", reported)

    def test_locally_defined_procedure_is_not_reported(self):
        findings = self.findings(self.SAMPLE)
        reported = {f.message.split("'")[1] for f in findings if f.check == "unknown-api"}
        self.assertNotIn("myDemoScript", reported)

    def test_exit_code_is_nonzero_when_errors_exist(self):
        path = Path(self.temp_dir.name) / "demo.il"
        path.write_text(self.SAMPLE, encoding="utf-8")
        code = self.validator.main([str(path), "--root", str(self.root)])
        self.assertEqual(code, 1)

    def test_exit_code_is_zero_for_clean_code(self):
        path = Path(self.temp_dir.name) / "clean.il"
        path.write_text('axlDbidName( axlDBCreateNet( "N1" ) )\n', encoding="utf-8")
        code = self.validator.main([str(path), "--root", str(self.root)])
        self.assertEqual(code, 0)

    def test_suggestion_points_at_the_right_real_api(self):
        findings = self.findings("axlNetRenameTo( o_net \"new\" )\n")
        self.assertIn("axlRenameNet", findings[0].message)


class BaselineTests(ValidatorTestBase):
    def test_measure_reports_the_expected_shape(self):
        examples = self.root / "examples"
        examples.mkdir()
        (examples / "good.il").write_text(
            'axlDbidName( axlDBCreateNet( "N1" ) )\n', encoding="utf-8"
        )
        (examples / "bad.il").write_text("axlInventedApi( 1 )\n", encoding="utf-8")
        measured = self.validator._measure(self.root)
        self.assertEqual(measured["example_files"], 2)
        self.assertEqual(measured["files_with_errors"], 1)
        self.assertEqual(measured["total_errors"], 1)
        self.assertEqual(measured["by_check"], {"unknown-api": 1})

    def test_check_fails_without_a_baseline(self):
        examples = self.root / "examples"
        examples.mkdir()
        (examples / "good.il").write_text("println( 1 )\n", encoding="utf-8")
        self.validator.BASELINE_PATH = Path(self.temp_dir.name) / "absent.json"
        self.assertEqual(self.validator.self_test(self.root, check=True), 1)

    def test_check_passes_when_baseline_holds(self):
        examples = self.root / "examples"
        examples.mkdir()
        (examples / "good.il").write_text("println( 1 )\n", encoding="utf-8")
        self.validator.BASELINE_PATH = Path(self.temp_dir.name) / "baseline.json"
        self.assertEqual(self.validator.self_test(self.root, write_baseline=True), 0)
        self.assertEqual(self.validator.self_test(self.root, check=True), 0)

    def test_check_fails_when_false_positives_rise(self):
        examples = self.root / "examples"
        examples.mkdir()
        (examples / "good.il").write_text("println( 1 )\n", encoding="utf-8")
        self.validator.BASELINE_PATH = Path(self.temp_dir.name) / "baseline.json"
        self.validator.self_test(self.root, write_baseline=True)
        # a new correct-by-vendor file the corpus cannot resolve regresses the gate
        (examples / "newer.il").write_text("axlBrandNewApi( 1 )\n", encoding="utf-8")
        self.assertEqual(self.validator.self_test(self.root, check=True), 1)


if __name__ == "__main__":
    unittest.main()
